site_name: Fusion
site_url: https://elttob.github.io/Fusion/
repo_name: Elttob/Fusion
repo_url: https://github.com/Elttob/Fusion

theme:
  name: material
  custom_dir: docs/assets/overrides
  logo: assets/logo-dark.svg
  favicon: assets/logo-dark.svg
  palette:
    scheme: fusion-dark
    primary: black
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/fusion.css

nav:
  - Home: index.md
  - Tutorials:
    - Get Started: tutorials/index.md
    - Instances:
      - Hello, Fusion!: tutorials/instances/hello-fusion.md
      - Handling Events: tutorials/instances/handling-events.md
    - Basic State:
      - State Objects: tutorials/basic-state/state-objects.md
      - Computations: tutorials/basic-state/computations.md
      - Properties & State: tutorials/basic-state/properties-&-state.md
    - "Project 1: Counting Clicks": tutorials/project-1-counting-clicks.md
    - More State:
      - Computing Arrays: tutorials/more-state/computing-arrays.md
      - Children & State: tutorials/more-state/children-&-state.md
    - Organisation:
      - Components: tutorials/organisation/components.md
      - Structure: tutorials/organisation/structure.md
    - "Project 2: To-Do List": tutorials/project-2-to-do-list.md
    - Tweens:
      - Simple Tweening: tutorials/tweens/simple-tweening.md
      - Tween Controllers: tutorials/tweens/tween-controllers.md
    - Springs:
      - Simple Springs: tutorials/springs/simple-springs.md
      - Spring Controllers: tutorials/springs/spring-controllers.md
    - "Project 3: Messaging": tutorials/project-3-messaging.md
  - Examples:
    - Home: examples/index.md
  - API Reference:
    - Home: api-reference/index.md
    - Luau Types: api-reference/luau-types.md
    - Errors & Messages: api-reference/errors-and-messages.md
    - Instances:
      - New: api-reference/new.md
      - Children: api-reference/children.md
      - OnEvent: api-reference/onevent.md
      - OnChange: api-reference/onchange.md
    - State Management:
      - State: api-reference/state.md
      - Computed: api-reference/computed.md
      - ComputedPairs: api-reference/computedpairs.md
    - Animation:
      - Tween: api-reference/tween.md
      - TweenController: api-reference/tweencontroller.md
      - Spring: api-reference/spring.md
      - SpringController: api-reference/springcontroller.md

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: false
