# Taken from roblox-ts under the MIT license https://github.com/roblox-ts/roblox-ts/blob/master/.github/workflows/ci.yml

name: CI

on:
  pull_request:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Selene
        run: selene src test benchmark
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Run StyLua check
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check src test benchmark
  unit-tests:
    name: Unit Tests
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build test place
        run: rojo build test-runner.project.json -o test.rbxl

      - name: Download OpenVPN
        run: choco install openvpn

      - name: Run OpenVPN
        run: Start-Process -FilePath "C:\\Program Files\\OpenVPN\\bin\\openvpn.exe" -ArgumentList "--config $((Resolve-Path .\\client.ovpn).Path)"

      - name: Poll for IP Change
        run: |
          $elapsed = 0
          while ($true) {
            try {
              $response = Invoke-WebRequest -Uri 'https://httpbin.org/ip' -Method GET -UseBasicParsing
              $content = ConvertFrom-Json $response.Content
              if ($content.origin -eq "104.238.130.74") {
                break
              }
            } catch {}
            if ($elapsed -ge 25) {
              Write-Error "Timeout reached!"
              exit 1
            }
            Write-Output "Polling.. Elasped: $elapsed, IP: $($content.origin)"
            Start-Sleep 5
            $elapsed += 5
          }
          Write-Output "Success!"

      - name: Validate Cookie
        run: |
          $session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
          $cookie = New-Object System.Net.Cookie
          $cookie.Name = ".ROBLOSECURITY"
          $cookie.Value = "${{ env.ROBLOSECURITY }}"
          $cookie.Domain = ".roblox.com"
          $session.Cookies.Add($cookie);
          Invoke-WebRequest "https://avatar.roblox.com/v1/avatar" -WebSession $session -UseBasicParsing

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          # This cookie is intentionally public, because secrets are not available in pull request CI runs
          # It is from an empty account and not a security vulnerability
          cookie: ${{ secrets.ROBLOSECURITY || '_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_110DEC190001D8119FFEBEB5D438E282F219AA711E40568ACBCBCFCAEFF411F4947B3B1D372497779069EDD8D4F0EBAE2DCC6A412C874CFBE3BA3BFFB52692B0E166FC956C2F4F6761BFE1EA11EB15DA3291C068585B7DF46A0EF04B75E895FDEC3AFB32751E8CFDE0C93C58A774E8DE337C003F3218B6566A6A90B904987E362FED4F6AF293FE430F88C0B9DB7DF75DD539632A2338346F5A55DD98BACB9E197D72358B3EFB878D096AD1F5906858CAAFAC33F0A74DBD078D0B8CC2EA9A67DAFDF31B8C69C3C224AAB34A0A2DDBD5D439E0620B7BBAD07F3DBE35C5BE11D5DEC3549D2368B08EE5707477B8365118CC6C4ACEB5DEB48D1DD1203E255C1EFB79233AF4076B36DFD3E1BAC7D2FA6F330505E9391894E8D3E6649755B035AE7450144318EF5BBE39505925937D16CE33F75A712FA57F6334C0AE5D9FEC702645BDCC5AF8BCE2AAB08488185AF3641C5D13AC8F281462F98BB630DF9CF4F3D934C4E75F4877D51A798F1B7684BB2541E218487965F5B1C511DF9F17A930B544543D76343B99' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        shell: bash
        run: run-in-roblox --place test.rbxl --script test-runner/Run.client.lua > test-out.txt
        continue-on-error: true

      - name: Screenshot
        if: failure()
        uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: 'desktop.jpg'

      - name: Check test status
        shell: bash
        run: cat test-out.txt | grep "0 failed, 0 skipped" || (cat test-out.txt && exit 1)
